// Resolved URL of the Amiga app icon, served from Vite's `public/`
// directory. The PNG is extracted from the built Android release APK
// (highest-resolution launcher icon, 432×432 RGBA) — i.e. exactly the
// brand mark the user sees on the Android home screen and in the
// app drawer.
//
// Why not src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher.png?
//   - That file is a small placeholder (3186 bytes, green square +
//     white "I") generated by `tauri android init`. The real brand
//     mark is generated downstream by the Android build pipeline
//     and packed into the APK at res/as.png / res/o-.png / etc.
//
// We keep the icon under public/ (not src/assets/) so it is served as
// a plain <img src=…> asset without going through Vite's asset
// pipeline. Re-syncing after a rebrand is:
//   1. rebuild Android release APK (`build-android.bat`)
//   2. node scripts/extract-android-icon.cjs
export const amigaIconUrl = "/amiga-icon.png";
